# Monitoring Dashboard Configuration

[prometheus]
# Prometheus server base URL
base_url = "http://localhost:9090"
# Request timeout in seconds
timeout_seconds = 10

[loki]
# Loki server base URL
base_url = "http://localhost:3100"
# Request timeout in seconds
timeout_seconds = 10
# Maximum number of logs to fetch
log_limit = 100

[ui]
# Refresh interval in seconds
refresh_interval_seconds = 5
# Number of log entries to display
log_display_count = 20